export const SUPABASE_URL = 'https://olfjbwyuusyambowcier.supabase.co'
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sZmpid3l1dXN5YW1ib3djaWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDkyMTEyMzYsImV4cCI6MjAyNDc4NzIzNn0.h6EWignB_qym26-jR_cZfH_kmx75lzmPWxdqywPsPGo'

